grundeinkommensbuero/website

src/components/CampaignVisualisations/index.js
src/components/Layout/index.js
src/hooks/Api/Crowdfunding/index.js

Resolves: https://trello.com/c/tpqKQleh
Fetches the crowdfunding data from Startnext before the overlay is loaded.
Changes:
* Adds function `buildVisualisationsWithCrowdfunding` in `hooks/Api/Crowdfunding` for returning a list of all visualisations where the visualisations with a startnext id have a new property `project`, which has the startnext project data as its value
* Extends `CrowdfundingVisualisation` to use the project data in props if the key exists, otherwise it will query the startnext api and load the project data.
* Use the `buildVisualisationsWithCrowdfunding` function in the layout to build a new overlay definition that can fetch the startnext project data before the overlay is opened.

Preload crowdfunding data for overlay.

---

src/components/CampaignVisualisations/index.js
src/components/Forms/SelfScan/index.js

Fixed a bug showing a wrong number of signatures already added on the form to self report signatures.
- Changed the useEffect dependency array that calls ''getSignatureCountOfUser' to listen to a change of state (as well as UserId and eMail). That way, the amount of signatures scanned by the user displays correctly whenever the form is saved or reopened.
- Removed 'AddSelfScanned' and 'AddedSelfScanned', because they are no longer needed
- When user clicks on 'Mehr eintragen', they do not have to reenter their email address. To make sure the data is submitted correctly, the email address will now be readded to the form object before submit.

SelfScan: Fixed display of signatures

---

src/components/CampaignVisualisations/index.js

Resolves https://trello.com/c/QHhn4TSb
I don't really love how on bigger screens now the text goes on the outside when there is plenty of room inside, but I think this solution is good for the time being.

Show visualisation count outside text < 50%

---

src/components/style/base.less
src/components/style/vars.less

Changes `.linkUnderlined()` which is also used in the header and the footer. Slightly increases line-height of `<h1 />`. To test, check those out and also other occurrences of `<h1 />`.
Before:
After: 
Trello: https://trello.com/c/DnTexNq1/563-025-blog-überschriften-link-underline-ist-seltsam

fix blog header links on hover

---

src/hooks/Authentication/index.js

As part of a strategy to only work with lowercase emails from now on I adjusted the sign up and sign in hooks to set emails to lowercase before passing them to the amplify functions.
To test: 
Sign up (e.g. via general pledge, does not have to be a new user) and sign in (also e.g. general pledge) with an email with uppercase letters and check (e.g. in the network analysis) if the email parameter was lowercased.

Lowercase email before sign up and sign in

---

src/hooks/Authentication/LocalStorageUser/index.js

Netlify logs a bunch of errors when builind because the error is caught. 
Error querying localStorage for user-id ReferenceError: window is not defined

Check for window before querying local storage

---

src/components/Forms/SelfScan/index.js
src/components/Forms/SelfScan/style.module.less
src/components/SignatureStats/index.js
src/components/SignatureStats/style.module.less
src/hooks/Api/Signatures/Get/index.js
src/pages/benutzer/ProfilePage/index.js
src/pages/benutzer/ProfilePage/style.module.less

https://trello.com/c/YiGiLtxH/607-profile-signature-collection-section-1
I extracted the signature stats of user from the self scan component into its own component and included that component into the profile page. 
Please do not hesitate to tell me if anything about the css or whatever seems a bit off or you would have done it differently. 
There was one thing that was a bit tricky: Because we wanted to inlcude a link to the self scan page we needed to check which campaign the user was part of the most recently. I did this inside the getSignatureCountOfUser hook. This could maybe be done in the self scan page in the future so that the visualisations could be shown depending on that. This would lead to us only needing one /qr page instead of /qr/b, /qr/hh etc. Maybe even some kind of …

Profile - Signature Collection Section

---

src/components/Forms/SignatureListDownload/index.js

When the user clicks the signature list, it was not reacting until the signup state was resolved. This shows the loading state on click, which makes the interface feel more responsive.

Handle loading of user signup state

---

src/components/CampaignVisualisations/index.js
src/components/CampaignVisualisations/style.module.less

When the target number of signatures has been reached, the bar displays in a different color.

Visualisations: Added blue background to completed bars

---

src/context/Authentication/index.js
src/hooks/Authentication/index.js
src/pages/mensch/ProfilePage/index.js

To test: navigation when opening profile as following.
Authenticated and different id:
- Inform user they are logged in as user, and trying to access user page that isn’t their own.
- Bounce back to identified state
- Option to go to own user page
- This requires secret code entry
Identified and own id:
- Inform user they are logged in as user, and that they just need to confirm their identity
- show secret code entry
Identified and different id:
- Inform user they are logged in as user, and trying to access user page that isn’t their own.
- Option to go to own user page
- This requires secret code entry
Unidentified:
- Inform user they are trying to access an user page. 
- Ask if they want to login. 
- Send to login page

Profile page mvp navigation

---

src/components/Forms/SignatureListDownload/index.js

Resolves: [https://trello.com/c/buBHjgCY](https://trello.com/c/buBHjgCY)
Simple test if the signature ID matches Berlin and removes the user’s option to print the signature list.

remove print option for berlin

---

src/components/Layout/Header/Menu/LoginMenuItem.jsx
src/pages/login/index.js

We pass the nextPage url param to the login page, so the user gets redirected to the page they were on before. 
In the login page component I put the parsing of query params into a use effect hook, since it was a bit inefficient before and led to issues with the /#code navigation.

Redirect to former page after login

---

src/components/Forms/SignatureListDownload/index.js
src/components/Layout/Sections/index.js
src/components/Layout/index.js
src/components/StaticPage/index.js

Prerequisite: Implemented a contentful checkbox to select if users can request signature lists by mail or not.
This PR **defaults to show** the user the option to request lists by mail. Unchecked radio boxes also show the option. 
**Only actively choosing "No" in contentful removes the option.**

Remove the request signature lists by mail option

---

src/components/Maps/LazyMap.js
src/components/StaticPage/index.js

**Required changes in Contentful**: All map objects need to have their config values updated. `bounds` should become `maxBounds`.
This allows the `<LoadableMap />` component to support setting a center and zoom from Contentful. 
It also makes the Contentful map config field's values passed directly in to the mapboxgl config. This means that any property supported by mapbox can be set in the Contentful config, and it will be applied. Make sure to update the query at `src/StaticPage` however.
By the way HIIII @Valioesi :) :)

Map support center and zoom.

---

src/components/CampaignVisualisations/index.js
src/components/Forms/Pledge/index.js
src/components/Forms/SignUp/index.js
src/components/Forms/SignUpFeedbackMessage/index.js
src/components/Forms/SignatureListDownload/index.js
src/components/Login/EnterLoginCode/index.js
src/components/Maps/LazyMap.js
src/components/StaticPage/index.js
src/hooks/Api/Signatures/Create/index.js
src/hooks/Authentication/AnswerChallenge/index.js
src/hooks/Authentication/index.js
src/pages/playground/karte.js
src/pages/playground/pledge.js
src/pages/playground/signIn.js
src/pages/unterschriftenliste/index.js

Resolves: https://trello.com/c/Zu19BEqH/734-registrierung-zu-passwordless-login-umbauen
When a new user signs up, the sign in flow is immediately called as well by sending the login code to the user. There the user flow for signing up and signing in is basically the same. 
The flow for the confirmation changed as well: users are already flagged as confirmed in cognito when signing up. But I introduced a separate confirmed flag in dynamo db. This flag is set to true as soon as the user has entered the correct login code and is thereby authenticated. 
The pr has to be tested locally because the backend is only deployed to dev stage so far. 
To test: 
- Downloading a signature list as authenticated user, non-authenticated user, identified user (by passing a user id as url param) and new user …

Passwordless auth

---

src/components/Forms/SignatureListDownload/index.js
src/components/utils/index.js

This is necessary for the new communication settings structure. When a new user downloads a list they will are simultaneously subscribing to the newsletter for that state. 
For future reference: we might also need to do something similar for our general sign up form. We can talk about that in the next sprint planning for example

Save newsletter settings when downloading list

---

src/hooks/Api/Municipalities/index.js
src/pages/playground/municipalityHook.js

Resolves: https://trello.com/c/DuEWV4p9/772-hook-f%C3%BCr-gemeindestatistiken-05
Pretty self explanatory. The one hook can be used for both endpoint (1. /analytics/municipalities, 2. /analytics/municipalities/{ags})
To test: go to /playground/municipalityHook and check the logs (only locally because the backend is only deployed to dev so far)

Hook to get stats for municipalities

---

src/components/Login/EnterLoginCode/index.js
src/hooks/Authentication/AnswerChallenge/index.js

There was an issue if a user wants to resend the code but has waited more than 3 minutes. In that case an error because of invalid session was thrown by Amplify. This is now caught and the sign in process is started again. A new code is sent.
To test: sign in as usual, sign in after resending code, resend code after waiting more than 3 minutes and sign in then.

Fixed issue when resending code after 3 min

---

src/components/Profile/ProfileWrapper/index.js

Send the login code without prompting email address if user visits profile while not authenticated. This is done through: Set user id to slug id, so people get immediately sent the login code.
This is relevant if people click a link in a newsletter to update contact settings.

Send code immediately if opening profile unauthenticated

---

src/components/Forms/DonationForm/index.js
src/components/Onboarding/Donate/index.js

Mehrere Glitches:
Wenn ich Überweisung auswähle, fehlt der Knopf mit (Weiter). Dadurch ist hier im Schlauch eine Sackgasse.
Wenn ich Lastschrift auswähle, und alles bestätigt habe (mit „Jetzt spenden“), steht im Danke-Screen der Button (Zur Startseite) - müsste (Weiter) heißen.
Wenn ich dann (Zur Startseite) klicke, komme ich zurück an den Anfang des Spendenschlauchs, sollte aber weiter zum nächsten Schlauchschritt „Teilen“ kommen.

Donation feature fixes

---

src/components/Forms/SignUp/index.js
src/context/Authentication/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1090240008?userId=17160996
1. Update user data when signing out
2. Check in form if zip codes is defined. This is more of a hotfix, because zip codes should always be there, but for some reason the municipality in the context does not contain zip codes anymore after signing out. I am looking into it...
To test:
1. Sign up for municipality -> stay on municipality page -> sign out -> open form and try signing up for municipality again
2. Sign in -> go to one of your municipalities -> sign out -> open form and try signing up for municipality again

Fix signout

---

static/_redirects

Newsletter link is /teilen/:userId, should be /teilen/?userId=:userId

hotfix link error in newsletter

---

src/components/Forms/SearchPlaces/index.js

The search for municipality sorts by population (again). But if the user searches for a zip code and there is an exact match, the exact match will be shown as top result. The rest of the results are sorted by population.

SearchPlaces: sort by population except if there is a exact zip code match

---

src/components/Layout/Sections/SectionComponentTextAndImage/index.js
src/components/Layout/Sections/TextAndImage/index.js
src/components/Layout/Sections/TextAndImage/style.module.less
src/components/Layout/Sections/index.js
src/components/StaticPage/index.js

Added a new contentful section that allows users to have a small image next to a bigger text. image can be left or right, component can be narrow or wide.
To test: Check out the section "Warum 1%?" on /bürgerbegehren. 
It should show up twice (old and new). I will delete the old section in Contentful before merging.

Section component text image

---

src/components/StaticPage/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1189728360?userId=17160996
I removed the title props in the graphql queries of the section components, because they weren't used anyway for some reason. I already changed the names of the contentful fields for all section components (title to name), I haven't changed the field ids yet though, because this pr would need to be merged beforehand. 
To test: nothing really, because the site wouldn't build if there were issues due to the changes.

Removed unused title props from graphql query

---

src/components/Layout/Sections/index.js
src/components/Municipality/MunicipalityCollectionMap/index.js
src/components/Municipality/MunicipalityProgress/index.js
src/components/StaticPage/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1223585208
Rewrote the entire thing. Instead of the hack a section component is included on the municipality page. There was already an existing prototype for a collection map for the municipality page (https://app.contentful.com/spaces/af08tobnb0cl/content_types/sectionComponentCollectionMap/fields).  I just changed it a bit and added the queries etc. The benefit now is that we can easily add collection maps via contentful to the municipality page and use the flags to define when to show them. Might soon be helpful for Berlin for example. 
To test:
Check the maps in different states (Bremen page, other pages, signed in, signed out, /gemeinden page, via homepage, etc). Thanks!

Collection Map: use contentful component instead of hack

---

src/hooks/Authentication/Verification/index.js
src/pages/verifizierung/index.js

The modified verification page now listens to url params userId and token. It sends them to a custom api endpoint (https://github.com/grundeinkommensbuero/backend/pull/102) to confirm the user.
To test: I have triggered an email to nicolai@expedition-grundeinkommen.de. Copy the params and open the /verifizierung page in a dev environment. Your user should get confirmed (maybe also check in db).

Changed verification page to use new custom api endpoint

---

gatsby-browser.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1096333332?userId=17160996
I added a function which runs on page load (and every time the route changes). It gets the hash from the url, looks for the id in the dom (multiple times every x ms, if internet is too slow) and then jumps to it. 
To test: check on multiple pages with anchors. E.g. /#map, /material#gesetzestexte, /presse/#pressespiegel and so on and so forth.

Workaround for anchors not working on page load

---

src/components/Login/EnterLoginCode/index.js
src/hooks/Authentication/AnswerChallenge/index.js
src/hooks/Authentication/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1264619042
The backend was rewritten and now uses a separate /users/sign-in endpoint, which creates a new login code, saves it in the cognito record and then emails it to the user. Therefore in the frontend the whole order of steps is skewed. 
Old: 
1) Show Email Form
2) Call Auth.signIn() 
3) Show Login Code Form
4) Call Auth.sendCustomChallengeAnswer()
New:
1) Show Email Form
2) Call /users/sign-in endpoint
3) Show Login Code Form
4) Call Auth.signIn(), which does not do a lot except for initializing the Cognito Flow
5) Call Auth.sendCustomChallengeAnswer()
The new Code is heavily influenced by https://tschoffelen.medium.com/serverless-magic-links-with-aws-cognito-92eff1351123. A lot of the code is basically …

Rewrote passwordless sign in

---

src/components/Forms/SearchPlaces/index.js

Kinda part of this issue: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1264623669
1) Fixed broken navigation through suggestions in Firefox. 
2) Focus into suggestions when pressing keydown while focused on input field.
3) When tabbing through suggestions, leave suggestion container after last result so there is a way to tab through form without being trapped in suggestions container. 
I don't have Safari, so maybe also check in Safari, since there seem to be differences in various browsers.

Search places suggestion navigation via keyboard

---

src/components/Forms/Meetup/index.js
src/components/Forms/Meetup/style.module.less
src/components/Maps/EventsListed.js
src/components/Maps/LazyMap.js
src/components/Maps/ShowMeetups.js
src/components/Maps/style.module.less
src/components/Maps/utils/dateStringManipulation.js
src/components/Maps/utils/utils.spec.js

This PR adds a list by day, of all collection events. To test, just look at `"/playground/karte"` and create an event, if not present, to see, if `"Heute"` and `"Morgen"` is correctly added as a label for events happening today and tomorrow.
Unfortunately it was not so easy to place the upcoming events in a two column layout, reading from top to bottom in the left column first, and the right column second. I would need to do some calculations to see how many events each day holds and group 50% of them into one group and the rest into another. This might make the logic even more complex. Let me know, if you can think of an easier way. :)

List public collection events by day

---

src/components/PledgePackage/ListPledgePackages/index.js

Due to backend changes I had to rename a key. 
See: https://github.com/grundeinkommensbuero/backend/pull/129

Packages: createdAt instead timestamp

---

src/components/Forms/SignatureListDownload/index.js
src/components/PledgePackage/CreatePledgePackage/index.js
src/components/utils/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1832417693
After package was created successfully the user is signed up for the municipality if not already the case. I did not introduce the state of the rest call, it's just being executed in the background. 
The user is not being signed up for the newsletter of the municipality though. I was unsure if it was the right place to do it. I can add that though. 
To test: go to mensch/{userId}/paket-nehmen?campaignCode={a campaign you are not signed up for, e.g. berlin-1) and create a package. You should be signed up for berlin then. If you replicate the steps, no new api call should be executed.

Sign up user for municipality after creating package

---

src/components/PledgePackage/ListPledgePackages/PledgePackageSection.js

Es ist vielleicht sinnvoll, statt userId isAuthenticated abzufragen, sonst werden im identifizierten Zustand die eigenen Pakete nicht angezeigt. 
Goto: /playground/packages
Beispiel identified state, obwohl ich packages habe.

Package: isAuthenticated instead userId

---

src/components/Forms/SignUp/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2181938009
Auf deutsch, damit ich es nicht nochmal tippen muss: 
Wir (ich glaub vor allem ich :D) haben bei der Umstellung, dass wir die Startseite nicht mehr morphen, aus irgendeinem Grund vergessen, den Signup besser zu handlen. Es wird immer noch immer nach dem Signup die Municipality im Context gesetzt, was an sich unproblematisch ist, außer die Person schließt dann das Modal. 
Es wird nun einfach statt des Setzens im Kontext direkt nach dem Signup zur Gemeindeseite navigiert. 
Testen: Eingeloggt und ausgeloggt für eine Gemeinde anmelden, Schlauch durchlaufen etc.

Navigate to municipality page after signup

---

src/components/BlogPost/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1116342442
There should now be the correct og image for blog posts. The properties of the featuredImage were not used correctly (maybe something changed in the api?). 
You can test the og image with the facebook debug tool:
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-377--expedition-grundeinkommen.netlify.app%2Fblog%2F2021%2F12%2F17%2F2022-wird-gross%2F

Fixed blog og image

---

src/components/Layout/Sections/style.module.less

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2211578795
Pretty self-explanatory:
Headings on sections with image should be black, not violet. E.g. on the blog

Black heading on image

---

src/components/Layout/Sections/index.js
src/components/Layout/Sections/style.module.less

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2488847138
You can now place section components within a three column layout by assigning column "leftThird", "centerThird" or "rightThird".
I created a static page under /test-dreier-layout for you to check out the layout or play around with: https://app.contentful.com/spaces/af08tobnb0cl/entries/2uvKbVsx2FJbi0OiVwuLHQ 
Also maybe check out, if the half half layout is not broken by the changes. Because I had to redefine the layout into six parts instead of four to accomodate for both layout possibilities.

Three column layout for components

---

src/components/Forms/Meetup/index.js
src/components/Maps/EventsListed.js
src/components/Maps/LazyMap.js
src/components/Maps/ShowMeetups.js
src/hooks/Api/Meetups/Create/index.js
src/hooks/Api/Meetups/Get/index.js
src/pages/playground/karte.js

I haven't come around to setting up a dev server yet, but we'll just use the prod backend until then. We'll just clean up all the data before the launch. You can go to /playground/karte and test creating an event and a list location.

Use two different endpoints for events and list locations

---

src/components/Forms/SignUp/index.js
src/pages/sammeln/aktiv-werden/index.js
src/pages/sammeln/anmelden/index.js
src/pages/sammeln/bild-hochladen/index.js

I now added in the backend (https://github.com/grundeinkommensbuero/backend/commit/fb7f40c256289993a911ccbcd1cf08d7f2178ab2) that you can add the extraInfo flag, so people are added to the "Aktivenverteiler". 
In the frontend on the signup page for collectors, the user is now being signed up for municipality (only berlin for now), general newsletter, berlin newsletter and berlin "Aktivenverteiler".

Collector signup newsletter

---

gatsby-node.js
src/components/Layout/Footer/index.js
src/components/Layout/Header/Menu/MenuItem.jsx
static/_redirects

Okay, got it to work. Had to...
1) Override all /berlin/* paths to /* in gatsby-node, but leave the slugs as is 
2) Override the paths in the menu and footer. This would not have been necessary, as we also could have changed the paths in contentful, but this makes testing and merging the pr easier. 
I also added a redirect from /berlin/* to /*, so the links that are already out there still work

Render /berlin/* as /*

---

src/components/Layout/Header/Menu/MenuItem.jsx
src/components/Layout/Header/Menu/index.jsx
src/components/Layout/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2629930227
It was already possible the add a MenuOberPunkt as child of a OberPunkt, but the code did not offer it (anymore?). 
I already added Draft entries in Contentful. To test, you can publish them, but it will break the build of master.

MenuOberpunkt as child in menu

---

src/components/Layout/Sections/style.module.less

Just a quick fix to make the partner logos look better.

Vertical centering for thirds components

---

src/components/PledgePackage/ListPledgePackages/Package.js
src/context/Snackbar/index.js

Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2653576246
This is my proposal to link the pledge package feature with our register signatures feature in the profile page. 
I first  experimented with displaying a link near the package. But it looked weird. The snackbar is probably better imo.

Pledge: show snackbar with link to self scan

---

src/components/Maps/EventsListed.js
src/components/Maps/style.module.less

Team members found the layout to be confusing and asked me to change it if possible (ideally just one column). It's now a wide column. I also tried a narrow centered column, but it looked kinda weird in context. 
We could also have the events of one day change between left and right column, but then we would still have the issue of white spaces. 
I also added the contact, which was missing.

Events list in one column and added contact

---

src/hooks/Api/Meetups/Create/index.js

It's not really possible to set a team member as the owner when creating an event via the website. So I am setting our team member (id 112) as a participant as default. 
I need to delete the test event as soon as you create one. Because it is written into the live db. So let me know :)

Set team member as default participant

---

src/components/Layout/Sections/style.module.less
src/components/style/baseBerlin.less

Links looked bad on the Berlin page, and spacing was off for the partner logos. Please check if it looks good in all browsers and screen sizes.

Berlin spacing fixes

---

backend-config.js
src/hooks/Api/Meetups/Get/index.js

Resolves not showing all future events. This is because I fetch all events and filter them out on the client (website). But there is a limit of 100 events being fetched. I could have adjusted the limit, but that's not really scalable. The server only returns future events if there is a user passed in the request (auth headers), I am not sure why. I also could have changed the server to alway return future events. But I wanted a quicker soluten, so I am now just passing a the auth headers of a default user.

Meetups: pass default user to only fetch future events

---

src/hooks/Api/Meetups/Get/index.js

List locations are now filtered by Volksentscheid Grundeinkommen initiative. Same for events, which was possible in the server beforehand, I just forgot to add it, it seems. 
This is a draft for now, because I need to wait for the app to be ready and then the server to be deployed.

Filter events and list locations by ini
