src/components/Forms/Pledge/index.js, src/components/Forms/SignatureCountSlider/index.js, src/components/Layout/Sections/index.js, src/components/StaticPage/index.js
adds possibility to identify different pledges
=> Add pledge ID

src/components/Forms/FormWrapper/index.js, src/components/Forms/FormWrapper/style.module.less, src/components/Forms/Pledge/index.js, src/components/Forms/SignUpFeedbackMessage/index.js, src/components/Forms/SignUpFeedbackMessage/style.module.less, src/components/Forms/Signatures/index.js, src/components/Forms/Signatures/style.module.less, src/components/Layout/Sections/index.js, src/components/StaticPage/index.js, src/components/utils/index.js
https://deploy-preview-31--dreamy-nightingale-49bc3f.netlify.com//test-unterschriften
=> Signatures: signup ui first iteration

README.md, src/components/Forms/Button/index.js, src/components/Forms/Pledge/index.js, src/components/Forms/Signatures/index.js, src/components/Layout/CTAButton/index.js, src/components/Layout/CTAButton/style.module.less, src/components/Layout/Footer/style.module.less, src/components/Layout/Header/index.js, src/components/Layout/Header/style.module.less, src/components/Layout/Sections/index.js, src/components/Layout/index.js, src/components/StaticPage/index.js, src/components/style/vars.less
=> Add menu & multiple CTA buttons

README.md, src/components/Forms/Button/index.js, src/components/Forms/Pledge/index.js, src/components/Forms/Signatures/index.js, src/components/Layout/CTAButton/index.js, src/components/Layout/CTAButton/style.module.less, src/components/Layout/Footer/style.module.less, src/components/Layout/Header/index.js, src/components/Layout/Header/style.module.less, src/components/Layout/Sections/index.js, src/components/Layout/index.js, src/components/StaticPage/index.js, src/components/style/vars.less
Reverts grundeinkommensbuero/website#32
=> Revert "Add menu & multiple CTA buttons"

src/components/Forms/SelfScan/index.js, src/hooks/Api/Signatures/Update/index.js, src/pages/qr/bb/index.js, src/pages/qr/sh/index.js
If we want to use user id instead of list id just change the url query param to userId=...
=> selfscan now also works with user id and email

package-lock.json, package.json, src/components/Confetti/index.js
DO NOT MERGE YET
demonstration for https://github.com/catdad/canvas-confetti/issues/104
=> Confetti: use new version 1.1.1 with worker

src/context/Authentication/index.js, src/hooks/Authentication/index.js, wrap-with-provider.js
=> lazy load amplify

src/components/SocialMedia/Share/index.js
param "status" needs to be "text"
=> bugfix Twitter share link

src/components/Layout/Header/style.module.less, src/components/style/vars.less
New try. 
@timurc I was unsure about using '!important', but it was already used a lot in the header styles, so I did the same. I assume that's what you meant by overwriting the header styles?
=> Changed header cta button border radius

src/components/utils/contentfulJsonToHtml.js
Solves https://trello.com/c/kVzkEOq2
All links to external pages should open in a new tab.
=> Open external links in a new tab

src/components/EnterLoginCode/index.js, src/components/Forms/Pledge/GeneralPledge.js, src/components/Forms/Pledge/SignaturePledge.js, src/components/Forms/SelfScan/index.js, src/components/Forms/Signatures/index.js, src/components/Layout/CTAButton/index.js, src/components/Layout/CTAButton/style.module.less, src/components/Login/EnterLoginCode/index.js, src/components/Login/RequestLoginCode/index.js, src/context/Authentication/index.js, src/hooks/Api/Pledge/Create/index.js, src/hooks/Api/Pledge/Update/index.js, src/hooks/Api/Signatures/Create/index.js, src/hooks/Api/Users/Get/index.js, src/hooks/Authentication/AnswerChallenge/index.js, src/hooks/Authentication/LocalStorageUser/index.js, src/hooks/Authentication/Verification/index.js, src/hooks/Authentication/index.js, src/pages/unterschriftenliste/index.js
Resolves: https://trello.com/c/KHG9dtGm
All userId state management in the authorisation context is using a new hook called `useLocalStorageUser` which is like a wrapper around useState that implements localStorage, to get the default values from localStorage, and update localStorage when the state is updated.
To represent the pseudo-login state, the state of `userId` will be the user ID acquired from local storage, authorisation, or the query string, while the isAuthenticated is `false`.
The fields available for user data is reduced in this state. Refer to **issues**.
Details:
- The `signOut` hook now uses the auth state to set the `userId` to undefined. This makes signOut work for cases where the user is authenticated, or pseudo-logged in.
- The query params are parsed in the …
=> Auth pseudo login state

src/components/Layout/index.js, src/context/Overlay/index.js
https://trello.com/c/5AqCbA7x
The overlay should not be activated when a user is filling out a form.
=> No overlay on input

src/components/utils/contentfulJsonToHtml.js
Should work now, could you test with `/entry-hyperlink-test`?
=> Contentful fix link type entry

src/components/Layout/Header/Menu/LoginMenuItem.jsx, src/components/Layout/Header/Menu/MenuItem.jsx, src/components/Layout/Header/Menu/MenuItemParent.jsx, src/components/Layout/Header/Menu/index.jsx, src/components/Layout/Header/Menu/style.module.less, src/components/Layout/Header/index.js, src/components/Layout/Header/style.module.less, src/context/Authentication/index.js
Implements the user login state in the top bar.
If user is logged in or identified, the email or userId is shown in the menu bar.
If the user isn't logged in, the menu isn't shown.
When the menu is hovered, the user can log out.
=> Show login state in menu bar

src/components/Layout/Header/style.module.less
To test: in authenticated or identified state check the menu on different screen sizes
https://trello.com/c/Rfx920sw/620-fix-menu-bar-on-small-layouts
=> Changed breakpoints for menu to avoid overlapping with logo

src/components/utils/index.js, src/pages/benutzer/ProfilePage/index.js, src/pages/benutzer/ProfilePage/style.module.less
- check if username exists and either show username or email
- show formatted createdAt date
https://trello.com/c/zfGrFLpi/606-profile-user-details-section-05
=> Profilepage: show email or username + creation date

src/components/Forms/SignUp/index.js
resolves: https://trello.com/c/oJ93I0D1/629-update-user-if-user-exists-when-signing-up-via-signupform-1
Adds the `updateUser` hook to the signup form, to send the `updatedOnXbge` field.
=> updateUser hook on signup

src/components/Login/RequestLoginCode/index.js
Test: go back in browser history after sending email in login form
Maybe not suuuper ideal that people can go forward again after going back, but in my opinion not a huge issue...
=> Go back to email form when pressing back button in enter login code

src/components/CampaignVisualisations/index.js, src/components/StaticPage/index.js
The link in the eye catcher can now be overwritten via contentful.
=> Fix for eye catcher link

package-lock.json, package.json, src/components/Forms/Button/index.js, src/components/Forms/Button/style.module.less, src/components/Forms/DonationForm/index.js, src/components/Forms/DonationForm/style.module.less, src/components/Forms/RadioButton/index.js, src/components/Forms/RadioButton/style.module.less, src/pages/mensch/ProfilePage/index.js, src/pages/mensch/ProfilePage/style.module.less
=> Donation feature component

src/components/Login/EnterLoginCode/index.js, src/hooks/Authentication/AnswerChallenge/index.js
Resolves: https://trello.com/c/NocPW1kI/783-gleichen-code-beim-login-erneut-senden-05  
To test: request to resend code when logging in. Only works locally because backend is only deployed to dev.   
Corresponding pr in backend: https://github.com/grundeinkommensbuero/backend/pull/64
=> Request to resend code now works with same code

src/components/Confetti/index.js, src/components/Forms/Checkbox/index.js, src/components/Forms/DonationForm/index.js, src/components/Forms/DonationForm/style.module.less, src/components/Forms/LabelInputErrorWrapper/index.js, src/components/Forms/SignUp/index.js, src/components/Forms/TextInput/index.js, src/components/Forms/ValidationError/index.js, src/components/Forms/ValidationError/style.module.less, src/components/Layout/Sections/index.js, src/components/Layout/Sections/style.module.less, src/components/Layout/index.js, src/components/Login/EnterLoginCode/index.js, src/components/Login/EnterLoginCode/style.module.less, src/components/StaticPage/index.js, src/hooks/Api/Users/Update/index.js, src/hooks/Authentication/AnswerChallenge/index.js
Includes all features necessary for the christmas donations
=> Christmas donations cherry pick

src/components/Forms/DonationForm/style.module.less, src/components/Layout/Sections/index.js, src/components/Layout/Sections/style.module.less
Some small changes that were requested after the feature went live.
=> Christmas donation finishes

src/components/Forms/DonationForm/index.js
Fixes a browser support issue with a positive lookbehind regex group in Safari (and possibly others).
=> fix regex browser compatibility

src/components/Layout/Sections/index.js, src/components/utils/contentfulJsonToHtml.js
To test: check the links "Sammellandkarte" and "support@expedition-grundeinkommen.de" in /bremen
=> small fixes in how links are handled in contentful body elements

src/components/Forms/Button/style.module.less, src/components/Forms/FinallyMessage/style.module.less, src/components/Forms/TextInput/style.module.less, src/components/Layout/CTAButton/style.module.less, src/components/Layout/Sections/style.module.less, src/components/StaticPage/index.js, src/components/TickerToSignup/Ticker/style.module.less, src/components/style/vars.less
Just some button styling. Might need some more adjustments later on.
=> Campaign launch more styles

src/components/InviteFriends/index.js, src/components/InviteFriends/style.module.less, src/components/Layout/Sections/index.js, src/components/Layout/Sections/style.module.less, src/components/Onboarding/Teilen/ShareButtonRow.js, src/components/Profile/ProfileTile/index.js, src/components/Profile/ProfileTile/style.module.less, src/components/TickerToSignup/index.js, src/components/utils/index.js, src/context/utils/index.js
Adds profile tile on landing page
=> Campaign launch profile tile

src/components/Layout/Sections/StandardSectionComponent/index.js, src/components/Municipality/MunicipalityMap/index.js, src/components/Municipality/MunicipalityMap/style.module.less, src/components/Municipality/MunicipalityMapAndSearch/index.js, src/components/Municipality/MunicipalityMapAndSearch/style.module.less
New layout according to wireframes, legend always shown
=> New layout for municipality map

src/components/Municipality/MunicipalityIntro/index.js, src/components/Municipality/MunicipalityMap/index.js, src/context/Municipality/index.js
Use the Municipality Context for stats. Context holds two states for stats (single and all). 
I am not quite sure how to check the changes in MunicipalityIntro, but it should work.
=> Stats in context

src/components/Municipality/MunicipalityMap/index.js
Removed condition, so map will be shown if there are no events
=> Show map even if there are no events

src/components/Forms/SearchPlaces/index.js
If user doesn't click on suggestion, the first suggestion should be chosen on blur, if the score is good enough.
=> Select municipality on blur

src/components/Forms/SignUp/index.js
If a municipality is set, we show different labels for Hamburg, Berlin, Bremen.
=> Show different nudge box labels for B, H, HB

src/components/Forms/SignUp/index.js
Only reinit form field which have not been touched
To test: Unauthenticated user, fill out form, chose Municipality with 1 zip code (e.g. Haan) and check if the form stays the same.
=> Don't reset email after municipality is selected

src/components/Municipality/MunicipalityInfoText/index.js, src/components/Municipality/MunicipalityIntro/index.js, src/components/Municipality/MunicipalityProgress/index.js, src/components/Onboarding/Donate/index.js, src/components/Onboarding/EngagementLevel/index.js, src/components/Onboarding/FinalNote/index.js
=> Municipality name error handling

src/components/Forms/SignUp/index.js
Bug: Ich kann das Formular nicht abschicken, wenn ich eingeloggt auf einer Gemeindeseite war und mich dort über den Button anmelden wollte.
Fixed it by updating user data when updateUserState is updated. Also made the loading animation smoother. We REALLY got to clean up the component soon. There is so much stuff in there from months ago (or one week ago), which is done so much differently now (e.g. feedback message etc)
To test: sign up on municipality page (most important), but also check signup on normal page and signup with new user
=> Bugfix: signup of municipality page

src/components/Login/EnterLoginCode/index.js
redirect to /registrieren/ insteag of /expedition/#generalpledge
=> update signup link

src/components/IntroText/logo-xbge-white.svg
...by changing the height of xbge logo
=> Make Fribis logo look a bit nicer

src/components/Onboarding/Share/SharePreview.js
Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1074828454
Updated lines start at 122. All of the changes are only due to prettier
To test: try sharing
=> Quickfix for sharing url if user id is undefined

src/components/Forms/SearchPlaces/index.js
Commented out sort by population in SearchPlaces component.
=> Search places: removed sort by population

src/components/IntroText/index.js, src/components/IntroText/style.module.less, src/components/TickerToSignup/index.js
=> Joyponader patch button swap

src/components/Municipality/MunicipalityMap/index.js, src/components/Municipality/MunicipalityMap/map-resources.md
This is just adding the small markdown list with links to tools that have been used in the municipality map.
=> added resources md and changed comment on backend scale

src/components/BecomeActive/style.module.less, src/components/Onboarding/Share/ShareButtonRow.js, src/components/Onboarding/Share/index.js, src/components/Onboarding/Share/style.module.less
Made the sharing feature on the municipalities pages look a bit nicer. 
Please check if it looks good on the municipality pages as well as the onboarding window.
=> Sharing feature styling

src/components/Municipality/MunicipalityMap/animate.js, src/components/Municipality/MunicipalityMap/index.js, src/components/Municipality/MunicipalityMap/style.module.less
and update initialMapAnimation flag behavior
=> add s3 bucket link to fallback 

src/components/Layout/Sections/index.js, src/components/Login/EnterLoginCode/index.js, src/components/Onboarding/Share/index.js, src/components/Onboarding/Share/style.module.less
Nothing much to test here, but it makes Contentful variables in the Sharing Component optional, they can now be empty.
=> Optionalizes ShareFeature Contentful dependencies

src/components/Forms/DonationForm/index.js, src/components/Forms/SignUp/index.js, src/components/Layout/Sections/index.js, src/components/Login/RequestLoginCode/index.js, src/components/Municipality/MunicipalityMap/index.js, src/components/Onboarding/Share/ShareButtonRow.js, src/components/Onboarding/Share/SharePreview.js
I removed some variables and functions that are no longer needed to remove console warnings. Also some prettier formatting happened automatically.
To test: Look at the code, see if there is anything you want to keep. (does it spark joy?)
Also have a look around and check that everything still works (I don't know why it shouldn't, but you never know...).
=> Cleanup warnings

src/components/CrowdfundingInfo/CrowdfundingVisual.js, src/components/CrowdfundingInfo/index.js, src/components/Layout/Header/StickyDonationBar/HertieCrowdfunding.jsx
Currency symbol added, link changed, small text changes
=> Crowdfunding Banner 

src/components/CampaignVisualisations/index.js, src/components/Forms/SelfScan/CampaignScanVisualisation.js, src/components/Forms/SelfScan/index.js, src/components/Forms/SelfScan/style.module.less, src/components/Profile/ProfileOverview/index.js, src/components/Profile/ProfileSignatures/campaignCodes.json, src/components/Profile/ProfileSignatures/index.js, src/components/Profile/ProfileSignatures/style.module.less, src/components/Profile/ProfileTile/style.module.less, src/hooks/Api/Signatures/Update/index.js
The ProfileSignatures component checks available municipalities in userData and compares to a list of campaigns, actively collecting signatures.
Not sure if "Brandenburg" and "Schlesweg-Holstein" are covered yet, because they don't have an ags property. (How are their participating users saved?)
Furthermore it needs to be extended with other qualified and collecting municipalities in the future.
=> Signatures in profile, for users municipalities

src/components/Login/EnterLoginCode/index.js, src/hooks/Authentication/AnswerChallenge/index.js, src/hooks/Authentication/index.js
Revert sign in changes because of issues when opening profile direclty
=> Revert "Rewrote passwordless sign in"

src/components/Layout/Header/StickyDonationBar/hertieStyle.module.less
Hands going up and down. Basically just used the simple animation from the hurray crowd we used to show.
=> Animate hands in crowdfunding banner

src/components/BlogList/style.module.less
Removed grayscale in blog list, upped saturation
=> Blog image filter change

src/components/Login/EnterLoginCode/index.js, src/hooks/Authentication/AnswerChallenge/index.js, src/hooks/Authentication/index.js
I reverted the last pull request because I noticed a bug after merging. When visiting the route /mensch/{userId} route the sign in was broken. I totally forgot to account for that and therefore also did not ask you to test it. 
The newest commits fix the issue. Therefore I wanted to ask for a re-review. Sorry for the inconvencience. 
You probably don't need to test as thoroughly as before, because the usual signup/signin did not change much, but maybe also check the /mensch route again.
=> Rewrite login fixes

src/components/Layout/Header/StickyDonationBar/HertieCrowdfunding.jsx, src/components/Layout/Header/StickyDonationBar/hertieStyle.module.less, src/components/Layout/Header/StickyDonationBar/index.jsx, src/components/Layout/Sections/index.js, src/components/Municipality/Leaderboard/Table/PageSelector.jsx, src/components/Municipality/Leaderboard/Table/TabSelector.jsx, src/components/Municipality/Leaderboard/style.module.less, src/components/Onboarding/BreadcrumbLinks.js, src/components/Onboarding/Share/SharePreview.js, src/components/Onboarding/Share/index.js, src/components/Onboarding/index.js, src/components/Onboarding/style.module.less, src/components/style/vars.less
To test:
Onboarding: close first page (login) with keyboard
Leaderboard: Switch tabs and pages with keyboard
Banner: Close Banner with keyboard (space and enter)
=> Accessibility improvement

src/components/Profile/PersonalSettings/ChangeEmail.js, src/components/Profile/PersonalSettings/EnterCode.js, src/components/Profile/PersonalSettings/index.js, src/components/Profile/style.module.less, src/hooks/Authentication/index.js
I added functionality to change one's email address in the profile settings. An amplify function is used to change the email address in cognito and trigger an email with a code to verify the new email. If user aborts the verification process the new email will be verified during the next login (see: https://github.com/grundeinkommensbuero/backend/pull/118)
=> Ability to change email address in profile

src/components/Forms/FinallyMessage/index.js, src/components/Forms/Pledge/index.js, src/components/Layout/Sections/index.js, src/components/StaticPage/index.js, src/hooks/Api/Pledge/Create/index.js
I already added the new pledge component in contentful. It is not shown in master because of the missing graphql call. If this pr is merged, the pledge will be shown for berlin (on the bottom of the page, can of course be moved in contentful)
=> Rewrite pledge to use new contentful structure

gatsby-node.js, src/components/BlogTeaser/index.js, src/components/Layout/Sections/RenderPage.js, src/components/Municipality/MunicipalityNews/index.js, src/components/Municipality/MunicipalityNews/style.module.less, src/pages/blog/index.js
Co-authored-by: Tatiana Schär <schaerta@users.noreply.github.com>
=> Filter out news in blog + render news component

src/components/Forms/SearchPlaces/style.module.less, src/components/Municipality/MapAndSearch/style.module.less
Two small bugfixes for Safari. To test, please check if code looks okay and if everything works in your browser. Thanks!
Tickets: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1557393589 and https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/1557293510
=> Safari leaderboard fix

src/components/BecomeActive/index.js, src/components/BecomeActive/style.module.less, src/components/Profile/ProfileTile/index.js, src/components/Profile/ProfileTile/style.module.less, src/components/style/vars.less
I changed the profile tile design so that it could fit next to the Section "Du willst noch mehr tun?" like in the design:
https://xd.adobe.com/view/9a37472d-b435-4cc2-bb13-cba74ec71402-cf64/screen/c3fbec6b-610b-4578-b9f8-c98f9d181a19
Note: The tile looks a bit stretched because it is still set to full size in Contentful. I will change it to 50% width as soon as this PR is merged. To check what the tile will look like, change its size to 50% in your browser dev tools.
=> Profile tile redesign

src/components/Layout/Header/index.js, src/components/Layout/Sections/index.js, src/components/Municipality/MapAndSearch/MunicipalityMoreDetails.jsx
Hide Nav-Button for selected municipality and Leaderboard on Berlin page
=> Municipality page requested changes

src/components/Forms/SignUp/index.js, src/components/Layout/Header/Menu/LoginMenuItem.jsx, src/components/Layout/Header/Menu/style.module.less, src/components/TickerToSignup/SignupButton/index.js, src/components/TickerToSignup/index.js, src/components/TickerToSignup/style.module.less
Some improvements after user tests.
Note: The linter complained when I tried to use an invisible link that just serves as a button. I also googled around and it just seems like a bad way of solving the problem. So I added an invisible heading instead, that should make the signup easier to find.
If you can think of anything else to add to improve a11y, please let me know!
=> Accessibility improvements

src/hooks/Authentication/AnswerChallenge/index.js, src/hooks/Authentication/index.js
Use track js library to track error during login.
You don't really have to test anything. Just check, if the code is alright.
=> Track login error

package-lock.json, package.json, src/components/Maps/LazyMap.js
Map did not load correctly. This is due to new es6 sturcture in mapbox v2. I fixed the issue following this guide: https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling
=> Workaround for mapbox bug

src/components/PledgePackage/ListPledgePackages/Package.js, src/components/PledgePackage/ListPledgePackages/PledgePackageSection.js, src/components/PledgePackage/ListPledgePackages/index.js, src/components/PledgePackage/ListPledgePackages/style.module.less, src/pages/playground/packages.js
This PR adds a component, that shows just a few pledge packages and links to the "Hall of Fame"
=> Show just a few packages

src/components/Municipality/MunicipalityGroups/index.js, src/components/PledgePackage/ListPledgePackages/PledgePackageSection.js
No need to test I guess, just resolving some Warnings and Errors. :)
=> A few very small fixes

src/components/Layout/Sections/FullscreenHero/index.js, src/components/Layout/Sections/FullscreenHero/style.module.less, src/components/Layout/Sections/index.js, src/components/Layout/Sections/style.module.less, src/components/StaticPage/index.js, src/components/style/vars.less
Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2488848095
Created new contentful section for a fullscreen hero image.
Goto /test-hero to check it out :)
=> Fullscreen hero image section

gatsby-node.js, static/_redirects
Render /berlin as / and don't render municipality pages in berlin project.
=> Berlin as home

src/components/Layout/index.js
"Mein Ort" should not show up in the menu on the Berlin Project Page.
=> removed "mein ort" for berlin project

src/components/Forms/FormSection/index.js, src/components/Forms/FormSection/style.module.less, src/components/Forms/SignUp/index.js, src/components/Forms/SmallSignup/index.js, src/components/Layout/Sections/index.js, src/components/StaticPage/index.js
Sign up form component with only email address. Already included on berlin page.
=> Small sign up form

src/components/Maps/EventsListed.js, src/components/Maps/LazyMap.js, src/components/utils/index.js, src/pages/sammeln/anmelden/index.js
I added a link to collector's registration in the collection map and the list of events.
=> Link to collector signup in collection map and list

src/components/Forms/SelfScan/index.js, src/components/HurrayCrowd/style.module.less, src/components/Modal/style.module.less, src/components/Profile/ProfileSignatures/campaignCodes.json, src/components/Profile/ProfileSignatures/index.js, src/components/SignatureListJourney/index.js, src/components/SignatureListJourney/style.module.less, src/hooks/Api/Signatures/Get/index.js
Added link to self scan in modal on checkpoints page .
Show berlin-2 campaign visualisations in profile and always show berlin visualisation by default on berlin website.
=> Checkpoints and self scan

src/components/Forms/SelfScan/index.js, src/components/Forms/SelfScan/style.module.less
In /unterschriften-eintragen in profile:
1) Add hint for list without bar code
2) Fixed mobile styling
=> Hint for list without bar code

src/components/Forms/SignatureListDownload/index.js, src/components/SignatureListJourney/index.js
Added info about online stamp services and innn.it cooperation to the signature list steps.
=> User journey additions

src/components/Maps/ShowMeetups.js
Depending on the path, we show only event or soli locations/storages
=> Different default states of collection map

src/components/Layout/index.js
"Mein Ort: Berlin" did not redirect to volksentscheid-grundeinkommen.de, because netlify redirects don't work at that stage. Redirect is now handled through code in the menu.
=> "Mein Ort" should redirect to berlin page

src/components/Forms/Meetup/index.js, src/components/Maps/LazyMap.js, src/hooks/Api/Meetups/Create/index.js
Pretty straighforward: added a contact field for list locations. List locations need to be removed after testing...
=> Contact field when creating list location

src/components/Forms/SmallSignup/index.js, src/components/StaticPage/index.js
A flag is passes through contentful, which is then saved in the user store. 
You can test on /to-work
=> Pass flag to small signup
